IMPORTS

1. How are these import methods different from eachother.
     -- import numpy
        -- This method is used to import a particular module (numpy in this case) and importantly it creates a reference to that module so that everything related to that module is stored in the same numpy namespace. After you import the module anything listed as numpy.___ will refer to this module.'
     -- from numpy import*
        -- This method imports the module and creates specific references to all of the objects/functions related to that module in the current namespace. So to run functions you wouldn't need to use numpy.___ you could simply say __. However, the only problem with that is if you have already defined ___ in another module it could get overwritten with this new uploaded module version, and if you ever change ___ later the module doesn't recognize the change.
     -- from numpy import random
        -- This will import just 'random' function from numpy instead of the entire module.

2. Which of the above do you think is preferred? Why?
        I think the preferred method is "import numpy" because this creates a defined namespace for that module and all of the functions inside of it. That eliminates any conflicts with functions of the same name in modules you already have downloaded or modules you download in the future.  

3. What happens to the stdlib module random if you run from numpy import random? Provide an example.
        **note to self- stdlib=standard library. If you do 'from numpy import random' the random function in your standard library on python will be overwritten and you won't be able to access it anymore. Instead when you use numpy.random that is the only random package available to you. 
Example : from numpy import random
          See example below. random.sample does not work because I have imported random from numpy. And you can see that when I use the np.random.random_sample that function does work. Note that I previously imported numpy as np. 
        
        
Sources: http://effbot.org/zone/import-confusion.htm (accessed 1/20/2016); http://www.gossamer-threads.com/lists/python/dev/650449 (accessed 1/20/2016); http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.sample.html#numpy.random.sample 

In [86]:
random.sample (range (1000000),10)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [87]:
5 * np.random.random_sample((3, 2)) - 5

array([[-3.8359272 , -3.79004801],
       [-2.22038734, -3.90443471],
       [-1.14528288, -0.82456538]])

PATHS

1. On your computer, create a file on the Desktop. What's the path to that file (e.g. the file path)? 
        Path to the file = C:\Users\Alicia\Desktop\test.docx

2. If you created a file in the root directory of your computer, what would that file path be?
        The file path in the root directory of windows isn't really that clear because the "root" changes based on your working directory. But say that you are planning on being in the C (hard drive directory) then the path would be C:\test.docx
    
3. On your computer, there is a setting/variable called ($PATH). What does that setting do?
        This setting allows you to "tell" Python about a specific location/directory on your computer.  When you update this variable with a new location any executable files you have in that location are now usable in Python because it knows where to find them. ***Note to Self: Windows always looks for executables in the current directory unless you update the path or you specify it*

4. On your computer, there is a setting/variable called {$PYTHONPATH}. What does that setting do? 
        This variable allows you to set the pather for importing python modules. So if you want to import a module you have saved in a different directory than python you can alter the PYTHONPATH to direct it to the new location to search for modules. 

MODULES

1. The module I plan to use is NumPy (fondly known in python as numpy).  This package is a fairly basic, but fundamentally important package for scientific computing on Python and it has the ability to handle data that Python cannot support.  Some of the more important features include the ability to use vectorized code which can increase the speed of calculations and can be written on fewere lines decreasing the potential for errors and making it easier to read/process. NumPy also helps to increase the statistical computation that can be done by Python by using a special array called ndarray which are of fixed size in oppostion of Python arrays that can grow dynamically.  What this really means is that the fixed array size allows NumPy to deal with large data sets at fast speeds with less codes. Furthermore, NumPy is integrated in or compatible with many other 3rd party modules/packages used on python, particuarily those useful in processing bioinformatics data sets. I think that NumPy will be useful for this class, and my future research, because it was created for use with biological datasets that are often too large or complicated for GUI interfaces to handle and could be slow if done using standard Python arrays. Already looking back at my thesis microsatellite data I am contemplating way I could have used NumPy to make sorting the data out much simpler for me. I have used that data in my one of my two examples. 

Sources: http://docs.scipy.org/doc/numpy-1.10.1/user/whatisnumpy.html (accessed 1/20/2016) ; http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf (accessed 1/21/2016)

In [21]:
import numpy as np

The above import numpy as np just imports the module so you can use its function as np.* when you want them. 

Example 1:
The np.arange function allows you to give a range of numbers and a value (in the below example 10) that you would like to find all of the values for every 10 between the two numbers in the range.  There is a particular instance I know this would be useful. When I did my allele counting for my microsatellites I had an approximate fragment size, but we were using tetranucleotide markers so the alleles could fall at any 4 bp within that size range and I had to manually determine what each of those values was. This was a tedious process and would have been so much easier to use a simple function like np.arange to determine the list. np.arange is show below in its simplest format. However, it can handle huge ranges, as well as floating decimals. You can set the format of the array you want printed (how many #s per line, do you want random #s from the range, etc). This could also be useful if you need to do research randomization. np.arange is a very powerful function when used with big data sets and more specifications.

Source: http://stackoverflow.com/questions/7267226/range-for-floats (accessed 1/20/2016)

In [20]:
np.arange( 456, 781, 10 )

array([456, 466, 476, 486, 496, 506, 516, 526, 536, 546, 556, 566, 576,
       586, 596, 606, 616, 626, 636, 646, 656, 666, 676, 686, 696, 706,
       716, 726, 736, 746, 756, 766, 776])

Example 2: In the below example I imported a small data set of my microsatellite allele data, which I named testofnumpy.txt) using np.fromfile.  I then told it that it was float data (so could be decimals), that it should count -1 or the whole sheet of data and that the data is separated by spaces (sep= ' ').  Then I used the np.sort function to arrange the alleles in increasing order so they are easier to look at. and determine if they are all actually tetranucleotides. This was a simplistic example, but used two of the organizational functions of numpy. 

Source: http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.fromfile.html (accessed 1/21/2016); http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.sort.html (accessed 1/21/2016)


In [60]:
a = np.fromfile ("c:/Users/Alicia/Desktop/Scripts/testofnumpy.txt", dtype=float, count=-1, sep=' ')
np.sort (a)

array([ 120.,  176.,  188.,  188.,  192.,  193.,  196.,  200.,  201.,
        201.,  203.,  204.,  214.,  214.,  218.,  224.,  227.,  228.,
        229.,  233.,  233.,  236.,  245.,  247.,  251.,  253.,  263.,
        263.,  270.,  289.,  292.,  300.,  301.,  304.,  305.,  308.,
        312.,  315.,  315.,  324.,  335.,  341.,  345.,  345.,  359.,
        398.,  430.,  430.,  537.,  637.,  643.,  643.])